import streamlit as st

st.title("Selamat Datang di Halaman Utama Kelompok 2")
st.write("This updated only to push commit..")

st.subheader("KESIMPULAN DAN SARAN")
st.write("""Kesimpulan : Penelitian ini bertujuan untuk menganalisis pengaruh faktor makroekonomi dan non-ekonomi terhadap aliran Foreign Direct Investment (FDI) di empat negara ASEAN, yaitu Indonesia, Malaysia, Thailand, dan Vietnam selama periode 2004–2023 dengan menggunakan pendekatan regresi data panel. Berdasarkan hasil pemilihan model melalui uji Chow, uji Lagrange Multiplier, dan uji Hausman, Random Effect Model (REM) ditetapkan sebagai model terbaik dalam menjelaskan hubungan antar variabel Hasil pengujian secara simultan (uji F) menunjukkan bahwa seluruh variabel independen yang digunakan dalam penelitian ini secara bersama-sama berpengaruh signifikan terhadap FDI di negara-negara ASEAN. Nilai Adjusted R-squared sebesar 39,09% mengindikasikan bahwa variasi FDI dapat dijelaskan oleh variabel GDP per kapita, nilai tukar, inflasi, suku bunga deposito, ekspor, kestabilan politik, dan pengendalian korupsi, sementara sisanya dipengaruhi oleh faktor lain di luar model penelitian.

                       Secara parsial, hasil penelitian menunjukkan bahwa GDP per kapita, nilai tukar, inflasi, dan suku bunga deposito berpengaruh signifikan terhadap FDI. GDP per kapita berpengaruh positif, yang menunjukkan bahwa semakin tinggi tingkat pendapatan dan daya beli masyarakat, semakin besar daya tarik suatu negara bagi investor asing. Nilai tukar yang signifikan menunjukkan bahwa stabilitas dan pergerakan kurs mata uang menjadi pertimbangan penting dalam keputusan investasi asing. Inflasi yang signifikan mengindikasikan bahwa tingkat inflasi yang terkelola masih dapat diterima investor sebagai bagian dari dinamika ekonomi. Sebaliknya, suku bunga deposito berpengaruh negatif terhadap FDI, yang menunjukkan bahwa tingkat suku bunga yang tinggi dapat mengurangi daya tarik investasi asing karena meningkatkan biaya modal.

                       Sementara itu, variabel ekspor, kestabilan politik, dan pengendalian korupsi tidak menunjukkan pengaruh signifikan terhadap FDI pada tingkat signifikansi 5%. Temuan ini mengindikasikan bahwa dalam periode dan negara yang diteliti, investor asing cenderung lebih mempertimbangkan faktor ekonomi makro dibandingkan faktor institusional dan politik, atau kemungkinan pengaruh variabel-variabel tersebut telah tercermin secara tidak langsung melalui variabel ekonomi lainnya.""")
